config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en/ do
    root 'pages#home'
    get  '/policy',            to: 'pages#policy'
    get  '/term',              to: 'pages#term'
    get  '/contact',           to: 'pages#contact'
  end

  get  '/search_meals',        to: 'pages#search_meals'
  get  '/search_meals_result', to: 'pages#search_meals_result'
  post '/contact_send',        to: 'pages#contact_send'

  #　(devise/confirmations#アクション)　＝＞　(japaneses/confirmation#アクション)に変更
  devise_for :japaneses, controllers: {
                                        registrations: 'japaneses/registrations',
                                        confirmations: 'japaneses/confirmations',
                                        sessions:      'japaneses/sessions',
                                        passwords:      'japaneses/passwords'
                                       }

  devise_for :foreigners, controllers: {
                                         registrations:      'foreigners/registrations',
                                         omniauth_callbacks: 'foreigners/omniauth_callbacks',
                                         sessions:           'foreigners/sessions',
                                         passwords:           'foreigners/passwords'
                                        }

    resources :japaneses,  only: [:show]
    resources :foreigners, only: [:show]
    resources :profiles, except: [:index, :show, :delete]

    resources :meals,shallow: true do
      resources :matches
      resources :favors, only: [:create, :destroy]
    end

    resources :rooms do
      resources :messages , only: [:create, :destroy]
    end
end

# == Route Map
#
#                                Prefix Verb     URI Pattern                                                                              Controller#Action
#                                  root GET      /(:locale)(.:format)                                                                     pages#home {:locale=>/en/}
#                                policy GET      (/:locale)/policy(.:format)                                                              pages#policy {:locale=>/en/}
#                                  term GET      (/:locale)/term(.:format)                                                                pages#term {:locale=>/en/}
#                               contact GET      (/:locale)/contact(.:format)                                                             pages#contact {:locale=>/en/}
#                          search_meals GET      /search_meals(.:format)                                                                  pages#search_meals
#                   search_meals_result GET      /search_meals_result(.:format)                                                           pages#search_meals_result
#                          contact_send POST     /contact_send(.:format)                                                                  pages#contact_send
#                  new_japanese_session GET      /japaneses/sign_in(.:format)                                                             japaneses/sessions#new
#                      japanese_session POST     /japaneses/sign_in(.:format)                                                             japaneses/sessions#create
#              destroy_japanese_session DELETE   /japaneses/sign_out(.:format)                                                            japaneses/sessions#destroy
#                 new_japanese_password GET      /japaneses/password/new(.:format)                                                        japaneses/passwords#new
#                edit_japanese_password GET      /japaneses/password/edit(.:format)                                                       japaneses/passwords#edit
#                     japanese_password PATCH    /japaneses/password(.:format)                                                            japaneses/passwords#update
#                                       PUT      /japaneses/password(.:format)                                                            japaneses/passwords#update
#                                       POST     /japaneses/password(.:format)                                                            japaneses/passwords#create
#          cancel_japanese_registration GET      /japaneses/cancel(.:format)                                                              japaneses/registrations#cancel
#             new_japanese_registration GET      /japaneses/sign_up(.:format)                                                             japaneses/registrations#new
#            edit_japanese_registration GET      /japaneses/edit(.:format)                                                                japaneses/registrations#edit
#                 japanese_registration PATCH    /japaneses(.:format)                                                                     japaneses/registrations#update
#                                       PUT      /japaneses(.:format)                                                                     japaneses/registrations#update
#                                       DELETE   /japaneses(.:format)                                                                     japaneses/registrations#destroy
#                                       POST     /japaneses(.:format)                                                                     japaneses/registrations#create
#             new_japanese_confirmation GET      /japaneses/confirmation/new(.:format)                                                    japaneses/confirmations#new
#                 japanese_confirmation GET      /japaneses/confirmation(.:format)                                                        japaneses/confirmations#show
#                                       POST     /japaneses/confirmation(.:format)                                                        japaneses/confirmations#create
#                 new_foreigner_session GET      /foreigners/sign_in(.:format)                                                            foreigners/sessions#new
#                     foreigner_session POST     /foreigners/sign_in(.:format)                                                            foreigners/sessions#create
#             destroy_foreigner_session DELETE   /foreigners/sign_out(.:format)                                                           foreigners/sessions#destroy
# foreigner_facebook_omniauth_authorize GET|POST /foreigners/auth/facebook(.:format)                                                      foreigners/omniauth_callbacks#passthru
#  foreigner_facebook_omniauth_callback GET|POST /foreigners/auth/facebook/callback(.:format)                                             foreigners/omniauth_callbacks#facebook
#                new_foreigner_password GET      /foreigners/password/new(.:format)                                                       foreigners/passwords#new
#               edit_foreigner_password GET      /foreigners/password/edit(.:format)                                                      foreigners/passwords#edit
#                    foreigner_password PATCH    /foreigners/password(.:format)                                                           foreigners/passwords#update
#                                       PUT      /foreigners/password(.:format)                                                           foreigners/passwords#update
#                                       POST     /foreigners/password(.:format)                                                           foreigners/passwords#create
#         cancel_foreigner_registration GET      /foreigners/cancel(.:format)                                                             foreigners/registrations#cancel
#            new_foreigner_registration GET      /foreigners/sign_up(.:format)                                                            foreigners/registrations#new
#           edit_foreigner_registration GET      /foreigners/edit(.:format)                                                               foreigners/registrations#edit
#                foreigner_registration PATCH    /foreigners(.:format)                                                                    foreigners/registrations#update
#                                       PUT      /foreigners(.:format)                                                                    foreigners/registrations#update
#                                       DELETE   /foreigners(.:format)                                                                    foreigners/registrations#destroy
#                                       POST     /foreigners(.:format)                                                                    foreigners/registrations#create
#                              japanese GET      /japaneses/:id(.:format)                                                                 japaneses#show
#                             foreigner GET      /foreigners/:id(.:format)                                                                foreigners#show
#                              profiles POST     /profiles(.:format)                                                                      profiles#create
#                           new_profile GET      /profiles/new(.:format)                                                                  profiles#new
#                          edit_profile GET      /profiles/:id/edit(.:format)                                                             profiles#edit
#                               profile PATCH    /profiles/:id(.:format)                                                                  profiles#update
#                                       PUT      /profiles/:id(.:format)                                                                  profiles#update

app/views/shared/_devise_errormes.html.erb
<% unless object.errors.empty? %>
  <script type="text/javascript">
    <% object.errors.full_messages.each do |value|%>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_english_meal_collection.html.erb
<% if Meal.count > 2 and @english_meals.count > 2 %>
  <section class="px-5 bg-white">
    <div class="mb-4 h3 w-100">
      <div class="ml-5 d-inline-block">
        <i class="fas fa-comment fa-lg"></i>
        <% if I18n.locale == :en %>
          <span class="mx-3">English</span>
        <% else %>
          <span class="mx-2 font-weight-bold" style="font-size:28px;"><span class="main-color">英語</span>を話そう</span>
        <% end %>
      </div>
      <span class="d-inline-block w-50 mt-3 ml-4" style="font-size:18px;color:pink;" data-toggle="modal" data-target="#how-to-read">
        <span class="how-to">
          <i class="far fa-question-circle"></i>
          <%= I18n.locale == :en ? "How to read a meal" : "投稿の読み方" %>
        </span>
      </span>
      <%= render 'shared/meal_explanation'%>
    </div>
    <div class="row justify-content-around">
      <%= render @english_meals %>
    </div>
    <div class="d-flex py-4 mx-3">
      <%= search_form_for @q, url: search_meals_result_path, class: "search_form mx-auto" do |f| %>
        <div class="form-group">
          <%= hidden_field_tag :foreigner_flng_id_eq, Language.first.id  %>
          <%= f.button class: "btn btn-darkblue-reverse search-button px-4", style: "height:40px;" do %>
            <span class="">
              <i class="fa fa-search mx-2"></i>もっと見る
            </span>
          <% end %>
        </div>
      <% end %>
    </div>
  </section>
<% end %>

app/views/shared/_footer_for_foreigner.html.erb
<footer id="main-footer" class="text-center pt-5 pb-4 bg-white text-dark">
  <div class="container">
    <div class="row">
      <div class="col-12 pb-3">
        <a href="#" class="text-secondary ml-2"><%= link_to "Terms of service", term_path(locale: :en), class:"text-muted"%></a>  |
        <a href="#" class="text-secondary mr-2"><%= link_to "Privacy Policy", policy_path(locale: :en), class:"text-muted"%></a>  |
        <a href="#" class="text-secondary mx-2"><%= link_to "Contact", contact_path(locale: :en), class:"text-muted"%></a>
      </div>
      <div class="col-12">
        <p class="text-secondary">&copy; BiliBuddy</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header_message.html.erb
<li class="nav-item dropdown mr-4 ml-2">
  <a class="nav-link dropdown-toggle mt-1" href="#" id="dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= link_to '#', class: "nav-link p-0" do %>
      <i class="far fa-handshake fa-lg mr-1"></i>
    <% end %>
  </a>
  <div class="dropdown-menu p-0" style="min-width:380px;left:-200px;" aria-labelledby="dropdown">
    <% if current_user.rooms.blank? %>
      <div class="p-3" style="font-size:15px;">
        <% if japanese? %>
          <div class="font-weight-bold" style="border-bottom:solid 2px black;">マッチングしたMealはありません。</div></br>
          世界中の人々が投稿したプランにオファーをし、承認されるのを待ちましょう。マッチングが完了したらメッセージを送れます。
        <% else %>
          <div class="font-weight-bold h5" style="border-bottom:solid 2px black;">No matched Meal</div></br>
          Post meal, wait until meal will be offered. Then, you can send message.
        <% end %>
      </div>
    <% else %>
      <table class="table mb-0" style="width:380px;border-radius:10px;">
        <thead class="thead text-white" style="background-color:#4682B4;">
          <tr>
            <th class="meal-th border-right" style="font-weight:900;"><i class="fas fa-list-ul fa-2x"></i></th>
            <th class="meal-th" style="font-size:14px;"><i class="fas fa-calendar-alt text-white mr-1"></i></br>DATE</th>
            <th class="meal-th" style="font-size:14px;"><i class="fas fa-clock text-white mr-1"></i></br>TIME</th>
            <th class="meal-th" style="font-size:14px;"><i class="fas fa-map-marker-alt text-white mr-1"></i></br>PLACE</th>
            <th class="meal-th" style="font-size:14px;"><i class="fas fa-users text-white mr-1"></i></br>PEOPLE</th>
          </tr>
        </thead>

        <tbody>
          <% current_user.rooms.each do |room| %>
            <tr class="tr_bottom" style="height:70px;" data-link="<%= room_path room %>" >
              <td class="meal-td">
                <% if current_user_exists? && foreigner? %>
                  <%= image_tag room.japanese.image.url(:_700), size: "45x45", class: "circle-image" %>
                <% else %>
                  <%= image_tag room.foreigner.image.url(:_700), size: "45x45", class: "circle-image" %>
                <% end %>
              </td>
              <td class="meal-td">
                <%= foreigner? ? room.meal.date.strftime("%d, %b") : room.meal.date.strftime("%m月%d日") %>
              <td class="meal-td"><%= room.match.meal.time %></td>
              <td class="meal-td">
                <%= room.match.meal.location.pick_locale %><br>
                (<%= room.match.meal.location.prefecture.pick_locale %>)
              </td>
              <td class="meal-td">
                <span style="font-size:20px;">
                  <%= room.match.meal.male + room.match.meal.female %> <span style="font-size:15px;"><%= t('ppl')%></span>
                </span>
              </br>
                ( <i class="fas fa-male fa-sm"></i><%= room.match.meal.male %> <i class="fas fa-female fa-sm"></i><%= room.match.meal.female %> )
              </td>
            </tr>

            <script>
              $("tr[data-link]").click(function() {
                window.location = $(this).data("link")
              })
            </script>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</li>

app/views/shared/_header_notification.html.erb
<li class="nav-item dropdown mr-4 ml-2">
  <a class="nav-link dropdown-toggle mt-1" href="#" id="dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= link_to '#', class: "nav-link p-0" do %>
      <i class="far fa-bell fa-lg mr-1"></i>
    <% end %>
  </a>
  <div class="dropdown-menu p-0" style="min-width:300px;left:-200px;" aria-labelledby="dropdown">
  </div>
</li>

app/views/shared/_logged_in_japanese_header.html.erb
<%= render 'shared/header_search' %>

<%= render 'shared/header_notification' %>

<%= render 'shared/header_message' %>

<li class="nav-item dropdown header-face ml-2">
  <a class="nav-link dropdown-toggle" href="#" id="dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= image_tag current_japanese.image.url(:_500), size: "45x45", style: "border-radius: 50%;" %>
  </a>
  <div class="dropdown-menu p-0" style="left:-20px;" aria-labelledby="dropdown">
    <span class="dropdown-item bg-darkorange" style="border-top-left-radius:3px;border-top-right-radius:3px;"></span>
    <%= link_to "プロフィール", japanese_path(current_japanese), class: "dropdown-item" %>
    <%= link_to "設定", edit_japanese_registration_path, class: "dropdown-item" %>
    <%= link_to "自己紹介", new_profile_path, class: "dropdown-item" %>
    <%= link_to "ミール", meals_path, class: "dropdown-item" %>
    <div class="dropdown-divider"></div>
    <%= link_to "ログアウト", destroy_japanese_session_path, method: :delete, class: "dropdown-item" %>
  </div>
</li>

app/views/shared/_meal_search_window.html.erb
<div class="d-flex py-4 mx-3">
  <%= search_form_for @q, url: search_meals_result_path, class: "search_form mx-auto" do |f| %>
    <div class="form-group">

      <div class="px-0 search-select d-inline-block mb-1">
        <%= f.collection_select :foreigner_flng_id_eq, Language.all, :id, :lang_ja, { prompt: "言語", include_blank: "選択なし" }, { class: "form-control text-muted", style: "height:40px;font-size:14px;width:115px;border-radius:3px !important;" } %>
      </div>

      <div class="px-0 search-select d-inline-block">
        <%= f.grouped_collection_select(:location_id_eq, Prefecture.all, :locations, :name_ja, :id, :name_ja, { prompt: "場所", include_blank: "選択なし" }, { class: "form-control text-muted", style: "height:40px;font-size:14px;width:115px;border-radius:3px !important;" } ) %>
      </div>

      <div class="px-0 search-select d-inline-block">
        <%= f.text_field :date_eq, placeholder: "日付", class: 'form-control bg-white', id: "datepicker", style: "height:40px;font-size:14px;width:115px;border-radius:3px !important;", autocomplete: 'off' %>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js"></script>
      </div>

      <div class="px-0 search-select d-inline-block">
        <%= f.select :time_eq,  [["00時 - 09時","0am-9am" ], ["09時 - 12時", "09am-12pm"],["12時 - 15時", "12pm-15pm"],["15時 - 18時", "15pm-18pm"],["18時 - 21時", "18pm-21pm"],["21時 - 24時", "21pm-24pm"] ], { prompt: "時間帯", include_blank: "選択なし" }, { class: "form-control text-muted", style: "height:40px;font-size:14px;width:115px;border-radius:3px !important;" } %>
      </div>

      <div class="px-0 search-select d-inline-block">
        <%= f.select :created_at, [["新着順", "DESC" ], ["古い順", "ASC"]], { prompt: "表示順"}, { class: "form-control text-muted", style: "height:40px;font-size:14px;width:115px;border-radius:3px !important;" } %>
      </div>

      <%= f.button class: "search-button", style: "border-color:#BBBBB;background-color:#EEEEEE;height:40px;" do %>
        <i class="fa fa-search mx-2"></i>
      <% end %>

      <div class="d-inline-block ml-3">
        <%= link_to search_meals_path do%>
          <i class="fas fa-redo faa-spin animated-hover fa-lg"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_message_toastr.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value|%>
     <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
     toastr['<%= type %>']('<%= value %>')
    <% end %>
  </script>
<% end %>

<!-- alert == error  notice == success
flash[:notice] = "sign in successfully"
↓
toastr['success']('sign in successfully') -->

app/views/shared/_new_meal_collection.html.erb
<% if Meal.count > 2 %>
  <section class="p-5 bg-white">
    <div class="h2 ml-4 font-weight-bold" style="margin-bottom:70px;">
      <span class="pt-2 pl-3" style="border-left:solid 5px #008BBB;">
        <%= I18n.locale == :en ? "Meals collection" : "外国人を探す"%>
      </span>
    </div>
    <div class="mb-4 h3 w-100">
      <div class="ml-5 d-inline-block">
        <i class="fas fa-plane-arrival fa-lg"></i>
        <% if I18n.locale == :en %>
          <span class="mx-3">Latest Meals</span>
        <% else %>
          <span class="mx-2 font-weight-bold" style="font-size:28px;">新着投稿</span>
        <% end %>
      </div>

      <span class="d-inline-block w-50 mt-3 ml-4" style="font-size:18px;color:pink;" data-toggle="modal" data-target="#how-to-read">
        <span class="how-to">
          <i class="far fa-question-circle"></i>
          <%= I18n.locale == :en ? "How to read a meal" : "投稿の読み方" %>
        </span>
      </span>
      <%= render 'shared/meal_explanation'%>
    </div>
    <div class="row justify-content-around">
      <%= render @new_meals %>
    </div>
    <% if I18n.locale == :ja %>
      <div class="d-flex py-4 mx-3">
        <%= search_form_for @q, url: search_meals_result_path, class: "search_form mx-auto" do |f| %>
          <div class="form-group">
            <%= hidden_field_tag :created_at, "DESC"  %>
            <%= f.button class: "btn btn-darkblue-reverse search-button px-4", style: "height:40px;" do %>
              <span class="">
                <i class="fa fa-search mx-2"></i>もっと見る
              </span>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </section>
<% end %>

app/views/shared/_offer_confirmation.html.erb
<div class="modal mx-auto bg-white" id="offer_modal_<%= meal.id %>" style="height:515px;z-index:1500;width:390px;border-radius:5px;margin-top:50px;">
  <div class="modal-dialog mt-0">
    <button class="close text-dark pr-3 pt-3" style="outline:none;" data-dismiss="modal">&times;</button>
  </div>
  <div class="pb-5 pt-5 text-center">
    <%= form_for([ meal, current_japanese.matches.build ], html: {class: "mb-3", style: "border-bottom:dotted 2px gray;"}) do |f| %>
      <div class="form-group mb-3" style="margin-right:22px;">
        <%= f.label :budget, "予算 (一人あたり)", class: "font-weight-bold h5 d-block main-color text-left ml-5" %>
        <%= f.select :budget,  [["〜1000円", 1000], ["〜1500円", 1500],["〜2000円", 2000],["〜3000円", 3000], ["〜4000円", 4000]], {}, { class: "form-control d-inline-block w-75", style: "height:47px;" }  %>
      </div>
      <div class="form-group mb-4">
        <%= f.label :skype, "事前にskype", class: "font-weight-bold h5 d-block main-color text-left ml-5" %>
        <%= f.select :skype, [["希望しない", 0], ["希望する", 1]], {}, { class: "form-control d-inline-block mr-4", style: "width:275px;height:47px;" }%>
      </div>
      <%= f.submit "オファーする", class: "btn btn-darkorange px-4 py-2 mr-3 mb-4", style: "border-radius:5px;" %>
    <% end %>
    <p class="mx-auto text-left mr-3 p-3 mt-4" style="background-color:#FADBDA;color:#FF0000;border-radius:3px;width:93%;line-height:1 !important;">
     <span class="font-weight-bold d-inline-block ml-2 h5">注意事項</span></br>
     <span style="font-size:10px;">
      ・オファーは相手との食事が決定されるものではなく、承認されないこともありますのでご了承ください。</br>
      ・自己紹介を充実させることによってオファーが承認される可能性が上がります。
     </span>
  </div>
</div>

app/views/shared/_profile_input.html.erb
<div class="row">
  <div class="h2 mb-5 mx-5 text-center w-100 border-bottom border-darkorange py-2">
    <% if japanese? %>
    自己紹介文
    <% else %>
    Introduction
    <% end %>
  </div>
  <div class="col-9 text-center mx-auto">
    <%= form_for @profile do |f| %>
      <%= render 'shared/devise_errormes', object: f.object %>

      <div class="form_control mb-4">
        <% if japanese? %>
          <%= f.text_area :intro, rows: "13", placeholder: "あなたの自己紹介を簡単な英語でなるべく多くご記入ください。例) なんと呼んで欲しいですか？好きなことはなんですか？どこらへんに住んでいますか？",  class: "form-control", style: "width:100% !important;" %>
        <% else %>
          <%= f.text_area :intro, rows: "13", placeholder: "Please write your profile in 500 words or less.",  class: "form-control", style: "width:100% !important;" %>
        <% end %>
      </div>

      <div class="profile-warning mx-auto text-left" style="font-size:10px;color:#999999;">
        <i class="warning-title fas fa-exclamation-circle mr-2 text-danger"></i>
        <% if japanese? %>
        BiliBuddyの基本は人間関係です。あなたのことを知ってもらいましょう！あなたの好きなもの、ことを教えたください。
        好きなことを５つ聞かれたらなんと答えますか？旅行は好きですか？将来どんなことがしたいですか？人々にあなたの性格についても教えてあげましょう。
        <% else %>
        The basis of BiliBuddy is human relations. Let 's make an effort to get to know yourself.
        Please tell me what you like. What would you say if you are asked five things you could not live without this? What is your favorite destination,
        book, movie, program, music and off course Japanese, food? Please tell me the style of your trip (commitment, style). Let people know your personality as well. What is the motto of life?
        <% end %>
      </div>
      <div class="actions text-center mt-4 mb-5 h5">
        <% if japanese? %>
        　<%= f.submit "送信する", class: "btn btn-darkorange btn-lg px-5 py-2", style: "border-radius:10px;" %>
        <% else %>
        　<%= f.submit "Submit", class: "btn btn-darkorange btn-lg px-5 py-2", style: "border-radius:10px;" %>
        <% end %>
      </div>

    <% end %>
  </div>
</div>

app/views/shared/_registration_modal.html.erb
<div class="modal" id="registration_modal">
  <div class="modal-dialog py-5" style="z-index:1500;width:390px;border-radius:20px;">
    <div class="modal-content">
      <div class="modal-header p-1 border-white">
        <button class="close text-dark" style="outline:none;" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body py-4 px-3 text-center">
        <% if I18n.locale == :en %>
          <div style="font-size:15px;">
            <div style="filter:drop-shadow(3px 3px 2px rgba(0,0,0,0.5));">
              <%= button_to "Sign up as Foreigner", new_foreigner_session_path, class: "btn btn-darkorange btn-lg px-4 font-weight-bold", style: "border-radius:5px;", method: :get%>
            </div>
            <div class="my-4 h4">----------- or -----------</div>
            <div class="mb-4">
              <%= link_to "Sign up as Japanese", new_japanese_registration_path, class: "font-weight-bold text-muted h5", method: :get%>
            </div>
          </div>
        <% else %>
          <div style="font-size:13px;">
            <div style="filter:drop-shadow(3px 3px 2px rgba(0,0,0,0.5));">
              <%= button_to "日本人で登録", new_japanese_registration_path, class: "btn btn-darkorange btn-lg px-5 m-auto font-weight-bold", style: "border-radius:5px;", method: :get%>
            </div>
            <div class="my-4 h4">----------- or -----------</div>
            <div class="mb-4">
              <%= link_to "外国人で登録", new_foreigner_session_path, class: "font-weight-bold text-muted h5", method: :get%>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_request_confirmation.html.erb
<div class="modal mx-auto bg-white" id="request_modal_<%= meal.id %>" style="height:515px;z-index:1500;width:390px;border-radius:5px;margin-top:50px;">
  <div class="modal-dialog mt-0">
    <button class="close text-dark pr-3 pt-3" style="outline:none;" data-dismiss="modal">&times;</button>
  </div>
  <div class="pb-5 pt-5 text-center">
    <%= form_for([ meal, current_japanese.matches.build ], html: {class: "mb-3", style: "border-bottom:dotted 2px gray;"}) do |f| %>
      <div class="form-group mb-3" style="margin-right:22px;">
        <%= f.label "予算 (一人あたり)", class: "font-weight-bold h5 d-block main-color text-left ml-5" %>
        <%= f.select :budget,  [["〜1000円", 1000], ["〜1500円", 1500],["〜2000円", 2000],["〜3000円", 3000], ["〜4000円", 4000]], {}, { class: "form-control d-inline-block w-75", style: "height:47px;" }  %>
      </div>
      <div class="form-group mb-4">
        <%= f.label :skype, "事前にskype", class: "font-weight-bold h5 d-block main-color text-left ml-5" %>
        <%= f.select :skype, [["希望しない", 0], ["希望する", 1]], {}, { class: "form-control d-inline-block mr-4", style: "width:275px;height:47px;" }%>
      </div>
      <%= f.submit "オファーする", class: "btn btn-darkorange px-4 py-2 mr-3 mb-4", style: "border-radius:5px;" %>
    <% end %>
    <p class="mx-auto text-left mr-3 p-3 mt-4" style="background-color:#FADBDA;color:#FF0000;border-radius:3px;width:93%;line-height:1 !important;">
     <span class="font-weight-bold d-inline-block ml-2 h5">注意事項</span></br>
     <span style="font-size:10px;">
      ・オファーは相手との食事が決定されるものではなく、承認されないこともありますのでご了承ください。</br>
      ・自己紹介を充実させることによってオファーが承認される可能性が上がります。
     </span>
  </div>
</div>

app/views/shared/_setting_meal.html.erb
<div class="d-flex flex-column mb-5 mx-auto" style="font-size:16px;max-width:460px;border-radius:12px;border:solid 1px #EEEEEE">
  <%= render 'shared/setting_meal_inside', meal: meal %>
</div>