config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en/ do
    root 'pages#home'
    get  '/policy',            to: 'pages#policy'
    get  '/term',              to: 'pages#term'
    get  '/contact',           to: 'pages#contact'
  end

  get  '/search_meals',        to: 'pages#search_meals'
  get  '/search_meals_result', to: 'pages#search_meals_result'
  post '/contact_send',        to: 'pages#contact_send'

  #　(devise/confirmations#アクション)　＝＞　(japaneses/confirmation#アクション)に変更
  devise_for :japaneses, controllers: {
                                        registrations: 'japaneses/registrations',
                                        confirmations: 'japaneses/confirmations',
                                        sessions:      'japaneses/sessions',
                                        passwords:      'japaneses/passwords'
                                       }

  devise_for :foreigners, controllers: {
                                         registrations:      'foreigners/registrations',
                                         omniauth_callbacks: 'foreigners/omniauth_callbacks',
                                         sessions:           'foreigners/sessions',
                                         passwords:           'foreigners/passwords'
                                        }

    resources :japaneses,  only: [:show]
    resources :foreigners, only: [:show]
    resources :profiles, except: [:index, :show, :delete]

    resources :meals,shallow: true do
      resources :matches
      resources :favors, only: [:create, :destroy]
    end

    resources :rooms do
      resources :messages , only: [:create, :destroy]
    end
end

# == Route Map
#
#                                Prefix Verb     URI Pattern                                                                              Controller#Action
#                                  root GET      /(:locale)(.:format)                                                                     pages#home {:locale=>/en/}
#                                policy GET      (/:locale)/policy(.:format)                                                              pages#policy {:locale=>/en/}
#                                  term GET      (/:locale)/term(.:format)                                                                pages#term {:locale=>/en/}
#                               contact GET      (/:locale)/contact(.:format)                                                             pages#contact {:locale=>/en/}
#                          search_meals GET      /search_meals(.:format)                                                                  pages#search_meals
#                   search_meals_result GET      /search_meals_result(.:format)                                                           pages#search_meals_result
#                          contact_send POST     /contact_send(.:format)                                                                  pages#contact_send
#                  new_japanese_session GET      /japaneses/sign_in(.:format)                                                             japaneses/sessions#new
#                      japanese_session POST     /japaneses/sign_in(.:format)                                                             japaneses/sessions#create
#              destroy_japanese_session DELETE   /japaneses/sign_out(.:format)                                                            japaneses/sessions#destroy
#                 new_japanese_password GET      /japaneses/password/new(.:format)                                                        japaneses/passwords#new
#                edit_japanese_password GET      /japaneses/password/edit(.:format)                                                       japaneses/passwords#edit
#                     japanese_password PATCH    /japaneses/password(.:format)                                                            japaneses/passwords#update
#                                       PUT      /japaneses/password(.:format)                                                            japaneses/passwords#update
#                                       POST     /japaneses/password(.:format)                                                            japaneses/passwords#create
#          cancel_japanese_registration GET      /japaneses/cancel(.:format)                                                              japaneses/registrations#cancel
#             new_japanese_registration GET      /japaneses/sign_up(.:format)                                                             japaneses/registrations#new
#            edit_japanese_registration GET      /japaneses/edit(.:format)                                                                japaneses/registrations#edit
#                 japanese_registration PATCH    /japaneses(.:format)                                                                     japaneses/registrations#update
#                                       PUT      /japaneses(.:format)                                                                     japaneses/registrations#update
#                                       DELETE   /japaneses(.:format)                                                                     japaneses/registrations#destroy
#                                       POST     /japaneses(.:format)                                                                     japaneses/registrations#create
#             new_japanese_confirmation GET      /japaneses/confirmation/new(.:format)                                                    japaneses/confirmations#new
#                 japanese_confirmation GET      /japaneses/confirmation(.:format)                                                        japaneses/confirmations#show
#                                       POST     /japaneses/confirmation(.:format)                                                        japaneses/confirmations#create
#                 new_foreigner_session GET      /foreigners/sign_in(.:format)                                                            foreigners/sessions#new
#                     foreigner_session POST     /foreigners/sign_in(.:format)                                                            foreigners/sessions#create
#             destroy_foreigner_session DELETE   /foreigners/sign_out(.:format)                                                           foreigners/sessions#destroy
# foreigner_facebook_omniauth_authorize GET|POST /foreigners/auth/facebook(.:format)                                                      foreigners/omniauth_callbacks#passthru
#  foreigner_facebook_omniauth_callback GET|POST /foreigners/auth/facebook/callback(.:format)                                             foreigners/omniauth_callbacks#facebook
#                new_foreigner_password GET      /foreigners/password/new(.:format)                                                       foreigners/passwords#new
#               edit_foreigner_password GET      /foreigners/password/edit(.:format)                                                      foreigners/passwords#edit
#                    foreigner_password PATCH    /foreigners/password(.:format)                                                           foreigners/passwords#update
#                                       PUT      /foreigners/password(.:format)                                                           foreigners/passwords#update
#                                       POST     /foreigners/password(.:format)                                                           foreigners/passwords#create
#         cancel_foreigner_registration GET      /foreigners/cancel(.:format)                                                             foreigners/registrations#cancel
#            new_foreigner_registration GET      /foreigners/sign_up(.:format)                                                            foreigners/registrations#new
#           edit_foreigner_registration GET      /foreigners/edit(.:format)                                                               foreigners/registrations#edit
#                foreigner_registration PATCH    /foreigners(.:format)                                                                    foreigners/registrations#update
#                                       PUT      /foreigners(.:format)                                                                    foreigners/registrations#update
#                                       DELETE   /foreigners(.:format)                                                                    foreigners/registrations#destroy
#                                       POST     /foreigners(.:format)                                                                    foreigners/registrations#create
#                              japanese GET      /japaneses/:id(.:format)                                                                 japaneses#show
#                             foreigner GET      /foreigners/:id(.:format)                                                                foreigners#show
#                              profiles POST     /profiles(.:format)                                                                      profiles#create
#                           new_profile GET      /profiles/new(.:format)                                                                  profiles#new
#                          edit_profile GET      /profiles/:id/edit(.:format)                                                             profiles#edit
#                               profile PATCH    /profiles/:id(.:format)                                                                  profiles#update
#                                       PUT      /profiles/:id(.:format)                                                                  profiles#update

app/views/pages/contact.en.html.erb
<div class="mx-auto text-center p-4" style="font-size:14px;max-width:420px;min-width:300px;">
  <div class="h3 font-weight-bold main-color mb-5">CONTACT</div>
  <%= form_with url: contact_send_path, local: true do |f| %>
    <%= hidden_field_tag "locale", "en" %>

    <div class="form-group mx-auto mb-4">
      <%= f.text_field :name, autofocus: true, placeholder: "Name", class: "form-control", style: "height:50px;" %>
    </div>
    <div class="form-group mx-auto mb-4">
      <%= f.email_field :email, placeholder: "Email", class: "form-control", style: "height:50px;" %>
    </div>
    <div class="form-group mx-auto mb-5">
      <%= f.text_area :inquiry, placeholder: "Inquiry", class: "form-control align-top", style: "height:250px;" %>
    </div>
    <div class="form-group mx-auto mb-4">
      <%= f.submit "SEND", class: "form-control btn btn-darkorange py-2", style: "border-radius:5px;" %>
    </div>
  <% end %>
</div>

app/views/pages/contact.html.erb
<div class="mx-auto text-center p-4" style="font-size:14px;max-width:420px;min-width:300px;">
  <div class="h3 font-weight-bold main-color mb-5">CONTACT</div>
  <%= form_with url: contact_send_path, local: true do |f| %>
    <div class="form-group mx-auto mb-4">
      <%= f.text_field :name, autofocus: true, placeholder: "Name", class: "form-control", style: "height:50px;" %>
    </div>
    <div class="form-group mx-auto mb-4">
      <%= f.email_field :email, placeholder: "Email", class: "form-control", style: "height:50px;" %>
    </div>
    <div class="form-group mx-auto mb-5">
      <%= f.text_area :inquiry, placeholder: "Inquiry", class: "form-control align-top", style: "height:250px;" %>
    </div>
    <div class="form-group mx-auto mb-4">
      <%= f.submit "SEND", class: "form-control btn btn-darkorange py-2", style: "border-radius:5px;" %>
    </div>
  <% end %>
</div>

app/views/pages/contact.ja.html.erb
<div class="mx-auto text-center p-4" style="font-size:14px;max-width:420px;min-width:300px;">
  <div class="h3 font-weight-bold main-color mb-5">お問い合わせ</div>
  <%= form_with url: contact_send_path, local: true do |f| %>
    <div class="form-group mx-auto mb-4">
      <%= f.text_field :name, autofocus: true, placeholder: "お名前", class: "form-control", style: "height:50px;" %>
    </div>
    <div class="form-group mx-auto mb-4">
      <%= f.email_field :email, placeholder: "Email", class: "form-control", style: "height:50px;" %>
    </div>
    <div class="form-group mx-auto mb-5">
      <%= f.text_area :inquiry, placeholder: "お問い合わせ内容", class: "form-control align-top", style: "height:250px;" %>
    </div>
    <div class="form-group mx-auto mb-4">
      <%= f.submit "送信する", class: "form-control btn btn-darkorange py-2", style: "border-radius:5px;" %>
    </div>
  <% end %>
</div>

app/views/pages/home.en.html.erb
<section id="frist" class="py-4 bg-white">
  <div class="row">
    <div class="col-12 pt-4 pb-4 text-center">
      <h2 class="font-weight-bold mb-3 main-color" style="font-size:50px;">
        Free Meal <span class="d-inline-block">In Japan!</span>
      </h2>
      <% if !current_user_exists? %>
        <p class="mb-4 h5 text-muted font-weight-bold" style="font-size:23px;">Visit Japan, Talk Your language, <span class="d-inline-block pt-2">Great Moment</span></p>
        <input class="btn btn-darkorange btn-lg m-auto font-weight-bold" type="submit" value="Sign Up Now" data-toggle="modal" data-target="#registration_modal">
        <%= render 'shared/registration_modal' %>
      <% else %>
        <p class="mb-4 h5 text-muted font-weight-bold" style="font-size:23px;">Visit Japan, Talk Your language, <span class="d-inline-block pt-2">Great Moment</span></p>
        <%= link_to new_meal_path, class: "btn btn-darkorange btn-lg px-4 mt-4",style: "border-radius:10px;" do %>
          <span style="font-size:23px;">Create New Meal here</span>
        <% end %>
      <% end %>
    </div>
    <div class="col d-none d-lg-block">
      <%= image_tag 'people_lg.png', size: "640x180", class: "m-auto d-block"%>
    </div>
    <div class="col d-none d-md-block d-lg-none">
      <%= image_tag 'people_md.png', size: "530x190", class: "m-auto d-block"%>
    </div>
    <div class="col d-none d-sm-block d-md-none">
      <%= image_tag 'people_sm.png', size: "380x180", class: "m-auto d-block"%>
    </div>
    <div class="col d-block d-sm-none">
      <%= image_tag 'people_xs.png', size: "280x190", class: "m-auto d-block"%>
    </div>
  </div>
</section>

<section id="second" class="d-none d-lg-block">
  <div class="jumbotron">
    <div class="row">
      <div class="second-col col-md-4 offset-75 text-center text-white pt-4 pb-2 px-4 border" style="min-width:380px !important;">
        <h2 class="mb-4 mr-auto pb-2 border-bottom border-white">What's <span class="font-weight-bold word-edge d-inline-block"> BiliBuddy</span> ?</h1>
        <p class="text-left" style="line-height: 2;">
          BiliBuddy is web site which easily connects foreigner traveling or studying or working in Japan and the japanese who want to talk with foreigner, and help you meet up with the japanese. In return for chatting and teaching your language and exchanging cultures, they treat you to meal. Foreigner can also ask and know a lot about Japan. Let's spend great time with them.
        </p>
      </div>
    </div>
  </div>
</section>

<section id="second-2" class="p-5 d-block d-lg-none">
  <div class="row justify-content-center">
    <div class="second-col col-sm-10 text-center text-white p-3 mb-5">
      <h2 class="mb-4 mr-auto pb-2 border-bottom border-white">What's <span class="font-weight-bold word-edge d-inline-block"> BiliBuddy</span> ?</h1>
      <p class="pl-4 text-left pr-2" style="line-height:2;">
        BiliBuddy is web site which easily connects foreigner traveling or studying or working in Japan and the japanese who want to talk with foreigner, and help you meet up with the japanese. In return for chatting and teaching your language and exchanging cultures, they treat you to meal. Foreigner can also ask and know a lot about Japan. Let's spend great time with them.
      </p>
    </div>
    <div class="col-12 text-center mb-4 align-self-end">
      <%= image_tag 'bento.png', size: "350x350", class: "img-fluid" %>
    </div>
  </div>
</section>

<section id="third" class="pt-5 pb-2 bg-white">
  <div class="container">
    <div class="row text-center">
      <h1 class="col-12 mb-5 font-weight-bold">How to use <span class="d-inline-block main-color">BiliBuddy</span> ?</h1>
      <div class="col-lg-3 col-sm-6 mb-4">
        <i class="fas fa-paper-plane fa-5x faa-wrench animated-hover main-color mb-4"></i>
        <h5 class="font-weight-bold mb-3">1. Make post</h4>
        <p class="text-muted pl-4 text-left">Input your available date-time, place and number of people. (Maximum 3 people)</p>
      </div>
      <div class="col-lg-3 col-sm-6 mb-4">
        <i class="fas fa-hands-helping fa-5x faa-wrench animated-hover main-color mb-4"></i>
        <h5 class="font-weight-bold mb-3">2. Matching </h4>
        <p class="text-muted pl-4 text-left">Choose whether or not you accept offer from japanese when your post was offered. </p>
      </div>
      <div class="col-lg-3 col-sm-6 mb-4">
        <i class="fas fa-comments fa-5x faa-wrench animated-hover main-color mb-4"></i>
        <h5 class="font-weight-bold mb-3">3. Message </h4>
        <p class="text-muted pl-4 text-left">Chat about details of meal and let's know each other. You can also talk using skype.</p>
      </div>
      <div class="col-lg-3 col-sm-6 mb-4">
        <i class="fas fa-utensils fa-5x faa-wrench animated-hover main-color mb-4"></i>
        <h5 class="font-weight-bold mb-3">4. meet and eat</h4>
        <p class="text-muted pl-4 text-left">Enjoy conversation with local japanese and let's feel Japan more deeply.</p>
      </div>
    </div>
  </div>
</section>

<section id="forth" class="py-5">
  <div class="container">
    <div class="row text-center justify-content-center">
      <div class="col-12 pb-4 text-bold h1 font-weight-bold">
        Features of <span class="main-color d-inline-block">BiliBuddy</span>
      </div>
      <div class="col-lg-5 col-sm-12 borde my-2 mx-3 p-0">
        <div class="d-flex">
          <div class="p-4 align-self-start">
            <i class="far fa-check-circle fa-3x main-color"></i>
          </div>
          <div class="p-2 align-self-center text-left">
            No need to spend money in a restaurant at all. All you need is just transportation fare to the restaurant.
          </div>
        </div>
      </div>
      <div class="col-lg-5 col-sm-12 borde my-2 mx-3 p-0">
        <div class="d-flex">
          <div class="p-4 align-self-start">
            <i class="far fa-check-circle fa-3x main-color"></i>
          </div>
          <div class="p-2 align-self-center text-left">
          No need to be able to read Japanese menu order when you order food. The Japanese order best choice for you.
          </div>
        </div>
      </div>
      <div class="col-lg-5 col-sm-12 borde my-2 mx-3 p-0">
        <div class="d-flex">
          <div class="p-4 align-self-start">
            <i class="far fa-check-circle fa-3x main-color"></i>
          </div>
          <div class="p-2 align-self-center text-left">
            No need to have an acquaintance with local Japanese before using BiliBuddy. Just meet, eat and talk.
          </div>
        </div>
      </div>
      <div class="col-lg-5 col-sm-12 borde my-2 mx-3 p-0">
        <div class="d-flex">
          <div class="p-4 align-self-start">
            <i class="far fa-check-circle fa-3x main-color"></i>
          </div>
          <div class="p-2 align-self-center text-left">
            No need to be worried about person you will meet. If you want, You can talk with them beforehand by skype.
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<%= render 'shared/new_meal_collection' %>

app/views/pages/home.html.erb
<section id="frist" class="py-4 bg-white">
  <div class="row">
    <div class="col-12 pt-4 pb-4 text-center">
      <h2 class="font-weight-bold mb-3 main-color" style="font-size:32px;">
        Have A Free Meal <span class="d-inline-block">In Japan</span>
      </h2>
      <% if !current_user_exists? %>
        <p class="mb-4 h5 text-muted font-weight-bold" style="font-size:23px;">Visit Japan, Talk Your language, <span class="d-inline-block pt-2">Great Moment</span></p>
        <input class="btn btn-darkorange btn-lg m-auto font-weight-bold" type="submit" value="Sign Up Now" data-toggle="modal" data-target="#registration_modal">
        <%= render 'shared/registration_modal' %>
      <% else %>
        <p class="mb-4 h5 text-muted font-weight-bold" style="font-size:23px;">Visit Japan, Talk Your language, <span class="d-inline-block pt-2">Great Moment</span></p>
        <%= link_to new_meal_path, class: "btn btn-darkorange btn-lg px-4 mt-4",style: "border-radius:10px;" do %>
          <span style="font-size:23px;">Create New Meal here</span>
        <% end %>
      <% end %>
    </div>
    <div class="col d-none d-lg-block">
      <%= image_tag 'people_lg.png', size: "640x180", class: "m-auto d-block"%>
    </div>
    <div class="col d-none d-md-block d-lg-none">
      <%= image_tag 'people_md.png', size: "530x190", class: "m-auto d-block"%>
    </div>
    <div class="col d-none d-sm-block d-md-none">
      <%= image_tag 'people_sm.png', size: "380x180", class: "m-auto d-block"%>
    </div>
    <div class="col d-block d-sm-none">
      <%= image_tag 'people_xs.png', size: "280x190", class: "m-auto d-block"%>
    </div>
  </div>
</section>

<section id="second" class="d-none d-lg-block">
  <div class="jumbotron">
    <div class="row">
      <div class="second-col col-md-4 offset-75 text-center text-white pt-4 pb-2 px-4 border" style="min-width:380px !important;">
        <h2 class="mb-4 mr-auto pb-2 border-bottom border-white">What's <span class="font-weight-bold word-edge d-inline-block"> MEEaT JAPAN</span> ?</h1>
        <p class="text-left" style="line-height: 2;">
          MEEaT JAPAN is web site which easily connects foreigner traveling or studying or working in Japan and the japanese who want to talk with foreigner, and help you meet up with the japanese. In return for chatting and teaching your language and exchanging cultures, they treat you to meal. Foreigner can also ask and know a lot about Japan. Let's spend great time with them.
        </p>
      </div>
    </div>
  </div>
</section>

<section id="second-2" class="p-5 d-block d-lg-none">
  <div class="row justify-content-center">
    <div class="second-col col-sm-10 text-center text-white p-3 mb-5">
      <h2 class="mb-4 mr-auto pb-2 border-bottom border-white">What's <span class="font-weight-bold word-edge d-inline-block"> MEEaT JAPAN</span> ?</h1>
      <p class="pl-4 text-left pr-2" style="line-height:2;">
        MEEaT JAPAN is web site which easily connects foreigner traveling or studying or working in Japan and the japanese who want to talk with foreigner, and help you meet up with the japanese. In return for chatting and teaching your language and exchanging cultures, they treat you to meal. Foreigner can also ask and know a lot about Japan. Let's spend great time with them.
      </p>
    </div>
    <div class="col-12 text-center mb-4 align-self-end">
      <%= image_tag 'bento.png', size: "350x350", class: "img-fluid" %>
    </div>
  </div>
</section>

<section id="third" class="pt-5 pb-2 bg-white">
  <div class="container">
    <div class="row text-center">
      <h1 class="col-12 mb-5 font-weight-bold">How to use <span class="d-inline-block main-color">MEEaT JAPAN</span> ?</h1>
      <div class="col-lg-3 col-sm-6 mb-4">
        <i class="fas fa-paper-plane fa-5x faa-wrench animated-hover main-color mb-4"></i>
        <h5 class="font-weight-bold mb-3">1. Make post</h4>
        <p class="text-muted pl-4 text-left">Input your available date-time, place and number of people. (Maximum 3 people)</p>
      </div>
      <div class="col-lg-3 col-sm-6 mb-4">
        <i class="fas fa-hands-helping fa-5x faa-wrench animated-hover main-color mb-4"></i>
        <h5 class="font-weight-bold mb-3">2. Matching </h4>
        <p class="text-muted pl-4 text-left">Choose whether or not you accept offer from japanese when your post was offered. </p>
      </div>
      <div class="col-lg-3 col-sm-6 mb-4">
        <i class="fas fa-comments fa-5x faa-wrench animated-hover main-color mb-4"></i>
        <h5 class="font-weight-bold mb-3">3. Message </h4>
        <p class="text-muted pl-4 text-left">Chat about details of meal and let's know each other. You can also talk using skype.</p>
      </div>
      <div class="col-lg-3 col-sm-6 mb-4">
        <i class="fas fa-utensils fa-5x faa-wrench animated-hover main-color mb-4"></i>
        <h5 class="font-weight-bold mb-3">4. meet and eat</h4>
        <p class="text-muted pl-4 text-left">Enjoy conversation with local japanese and let's feel Japan more deeply.</p>
      </div>
    </div>
  </div>
</section>

<section id="forth" class="py-5">
  <div class="container">
    <div class="row text-center justify-content-center">
      <div class="col-12 pb-4 text-bold h1 font-weight-bold">
        Features of <span class="main-color d-inline-block">MEEaT JAPAN</span>
      </div>
      <div class="col-lg-5 col-sm-12 borde my-2 mx-3 p-0">
        <div class="d-flex">
          <div class="p-4 align-self-start">
            <i class="far fa-check-circle fa-3x main-color"></i>
          </div>
          <div class="p-2 align-self-center text-left">
            No need to spend money in a restaurant at all. All you need is just transportation fare to the restaurant.
          </div>
        </div>
      </div>
      <div class="col-lg-5 col-sm-12 borde my-2 mx-3 p-0">
        <div class="d-flex">
          <div class="p-4 align-self-start">
            <i class="far fa-check-circle fa-3x main-color"></i>
          </div>
          <div class="p-2 align-self-center text-left">
          No need to be able to read Japanese menu order when you order food. The Japanese order best choice for you.
          </div>
        </div>
      </div>
      <div class="col-lg-5 col-sm-12 borde my-2 mx-3 p-0">
        <div class="d-flex">
          <div class="p-4 align-self-start">
            <i class="far fa-check-circle fa-3x main-color"></i>
          </div>
          <div class="p-2 align-self-center text-left">
            No need to have an acquaintance with local Japanese before using MEEaT JAPAN. Just meet, eat and talk.
          </div>
        </div>
      </div>
      <div class="col-lg-5 col-sm-12 borde my-2 mx-3 p-0">
        <div class="d-flex">
          <div class="p-4 align-self-start">
            <i class="far fa-check-circle fa-3x main-color"></i>
          </div>
          <div class="p-2 align-self-center text-left">
            No need to be worried about person you will meet. If you want, You can talk with them beforehand by skype.
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<%= render 'shared/new_meal_collection' %>

app/views/pages/jcontact.html.erb
<div class="mx-auto text-center p-4" style="font-size:14px;max-width:420px;min-width:300px;">
  <div class="h3 font-weight-bold main-color mb-5">お問い合わせ</div>
  <%= form_with url: contact_send_path, local: true do |f| %>
    <div class="form-group mx-auto mb-4">
      <%= f.text_field :name, autofocus: true, placeholder: "お名前", class: "form-control", style: "height:50px;" %>
    </div>
    <div class="form-group mx-auto mb-4">
      <%= f.email_field :email, placeholder: "Email", class: "form-control", style: "height:50px;" %>
    </div>
    <div class="form-group mx-auto mb-5">
      <%= f.text_area :inquiry, placeholder: "お問い合わせ内容", class: "form-control align-top", style: "height:250px;" %>
    </div>
    <div class="form-group mx-auto mb-4">
      <%= f.submit "送信する", class: "form-control btn btn-darkorange py-2", style: "border-radius:5px;" %>
    </div>
  <% end %>
</div>

app/views/pages/search_meals.html.erb
<div class="mt-5 text-center main-color font-weight-bold h2">
  ミールを検索する
</div>

<%= render 'shared/meal_search_window' %>
<span class="d-inline-block w-50 ml-5" style="font-size:18px;color:pink;" data-toggle="modal" data-target="#how-to-read">
  <span class="how-to">
    <i class="far fa-question-circle"></i>
    投稿の読み方
  </span>
</span>
<%= render 'shared/meal_explanation'%>

<% if !@search_meals_result.nil? %>
  <div class="mx-5 mt-4">
    <% if @search_meals_result.blank? %>
    <div class="text-center font-weight-bold h5">
      該当のミールが見つかりませんでした.入力内容を変更して再度検索してみてください。
    </div>
    <% end %>
    <div class="meal-container">
      <%= render @search_meals_result %>
    </div>
    <div class="ml-5 mt-3">
      <%= paginate @search_meals_result %>
    </div>
  </div>
<% end %>