config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en/ do
    root 'pages#home'
    get  '/policy',            to: 'pages#policy'
    get  '/term',              to: 'pages#term'
    get  '/contact',           to: 'pages#contact'
  end

  get  '/search_meals',        to: 'pages#search_meals'
  get  '/search_meals_result', to: 'pages#search_meals_result'
  post '/contact_send',        to: 'pages#contact_send'

  #　(devise/confirmations#アクション)　＝＞　(japaneses/confirmation#アクション)に変更
  devise_for :japaneses, controllers: {
                                        registrations: 'japaneses/registrations',
                                        confirmations: 'japaneses/confirmations',
                                        sessions:      'japaneses/sessions',
                                        passwords:      'japaneses/passwords'
                                       }

  devise_for :foreigners, controllers: {
                                         registrations:      'foreigners/registrations',
                                         omniauth_callbacks: 'foreigners/omniauth_callbacks',
                                         sessions:           'foreigners/sessions',
                                         passwords:           'foreigners/passwords'
                                        }

    resources :japaneses,  only: [:show]
    resources :foreigners, only: [:show]
    resources :profiles, except: [:index, :show, :delete]

    resources :meals,shallow: true do
      resources :matches
      resources :favors, only: [:create, :destroy]
    end

    resources :rooms do
      resources :messages , only: [:create, :destroy]
    end
end

# == Route Map
#
#                                Prefix Verb     URI Pattern                                                                              Controller#Action
#                                  root GET      /(:locale)(.:format)                                                                     pages#home {:locale=>/en/}
#                                policy GET      (/:locale)/policy(.:format)                                                              pages#policy {:locale=>/en/}
#                                  term GET      (/:locale)/term(.:format)                                                                pages#term {:locale=>/en/}
#                               contact GET      (/:locale)/contact(.:format)                                                             pages#contact {:locale=>/en/}
#                          search_meals GET      /search_meals(.:format)                                                                  pages#search_meals
#                   search_meals_result GET      /search_meals_result(.:format)                                                           pages#search_meals_result
#                          contact_send POST     /contact_send(.:format)                                                                  pages#contact_send
#                  new_japanese_session GET      /japaneses/sign_in(.:format)                                                             japaneses/sessions#new
#                      japanese_session POST     /japaneses/sign_in(.:format)                                                             japaneses/sessions#create
#              destroy_japanese_session DELETE   /japaneses/sign_out(.:format)                                                            japaneses/sessions#destroy
#                 new_japanese_password GET      /japaneses/password/new(.:format)                                                        japaneses/passwords#new
#                edit_japanese_password GET      /japaneses/password/edit(.:format)                                                       japaneses/passwords#edit
#                     japanese_password PATCH    /japaneses/password(.:format)                                                            japaneses/passwords#update
#                                       PUT      /japaneses/password(.:format)                                                            japaneses/passwords#update
#                                       POST     /japaneses/password(.:format)                                                            japaneses/passwords#create
#          cancel_japanese_registration GET      /japaneses/cancel(.:format)                                                              japaneses/registrations#cancel
#             new_japanese_registration GET      /japaneses/sign_up(.:format)                                                             japaneses/registrations#new
#            edit_japanese_registration GET      /japaneses/edit(.:format)                                                                japaneses/registrations#edit
#                 japanese_registration PATCH    /japaneses(.:format)                                                                     japaneses/registrations#update
#                                       PUT      /japaneses(.:format)                                                                     japaneses/registrations#update
#                                       DELETE   /japaneses(.:format)                                                                     japaneses/registrations#destroy
#                                       POST     /japaneses(.:format)                                                                     japaneses/registrations#create
#             new_japanese_confirmation GET      /japaneses/confirmation/new(.:format)                                                    japaneses/confirmations#new
#                 japanese_confirmation GET      /japaneses/confirmation(.:format)                                                        japaneses/confirmations#show
#                                       POST     /japaneses/confirmation(.:format)                                                        japaneses/confirmations#create
#                 new_foreigner_session GET      /foreigners/sign_in(.:format)                                                            foreigners/sessions#new
#                     foreigner_session POST     /foreigners/sign_in(.:format)                                                            foreigners/sessions#create
#             destroy_foreigner_session DELETE   /foreigners/sign_out(.:format)                                                           foreigners/sessions#destroy
# foreigner_facebook_omniauth_authorize GET|POST /foreigners/auth/facebook(.:format)                                                      foreigners/omniauth_callbacks#passthru
#  foreigner_facebook_omniauth_callback GET|POST /foreigners/auth/facebook/callback(.:format)                                             foreigners/omniauth_callbacks#facebook
#                new_foreigner_password GET      /foreigners/password/new(.:format)                                                       foreigners/passwords#new
#               edit_foreigner_password GET      /foreigners/password/edit(.:format)                                                      foreigners/passwords#edit
#                    foreigner_password PATCH    /foreigners/password(.:format)                                                           foreigners/passwords#update
#                                       PUT      /foreigners/password(.:format)                                                           foreigners/passwords#update
#                                       POST     /foreigners/password(.:format)                                                           foreigners/passwords#create
#         cancel_foreigner_registration GET      /foreigners/cancel(.:format)                                                             foreigners/registrations#cancel
#            new_foreigner_registration GET      /foreigners/sign_up(.:format)                                                            foreigners/registrations#new
#           edit_foreigner_registration GET      /foreigners/edit(.:format)                                                               foreigners/registrations#edit
#                foreigner_registration PATCH    /foreigners(.:format)                                                                    foreigners/registrations#update
#                                       PUT      /foreigners(.:format)                                                                    foreigners/registrations#update
#                                       DELETE   /foreigners(.:format)                                                                    foreigners/registrations#destroy
#                                       POST     /foreigners(.:format)                                                                    foreigners/registrations#create
#                              japanese GET      /japaneses/:id(.:format)                                                                 japaneses#show
#                             foreigner GET      /foreigners/:id(.:format)                                                                foreigners#show
#                              profiles POST     /profiles(.:format)                                                                      profiles#create
#                           new_profile GET      /profiles/new(.:format)                                                                  profiles#new
#                          edit_profile GET      /profiles/:id/edit(.:format)                                                             profiles#edit
#                               profile PATCH    /profiles/:id(.:format)                                                                  profiles#update
#                                       PUT      /profiles/:id(.:format)                                                                  profiles#update

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :foreigner
  belongs_to :location
  has_many :matches, dependent: :destroy
  has_many :favors, dependent: :destroy
  has_many :japanese, through: :favors
  has_one  :room, dependent: :destroy

  NOBODY_IS_CHOSEN      = 0
  EXCESSIVE_ARE_CHOSEN  = 3
  MEAL_SAIZ_LIMITATION  = 5

  validates :date,         presence: true
  validates :time,         presence: true
  validates :skype,        inclusion: { in: [true, false] }
  validates :male,         numericality: { less_than: 4 }
  validates :female,       numericality: { less_than: 4 }
  validates :foreigner_id, presence: true
  validates :location_id,  presence: true

  validate :date_time_cannot_be_in_the_past
  validate :nobody_is_chosen
  validate :excessive_is_chosen

  def self.size_over?(foreigner)
    where(foreigner_id: foreigner).size < MEAL_SAIZ_LIMITATION
  end

  def already_offered?
    matches.exists?
  end

  def count_offer
    matches.where(meal_id: self, ok: 0).size
  end

  def already_matched?
    room
  end

  private

  def date_time_cannot_be_in_the_past
    errors.add(:date, "is past.") if date.present? && date < Date.current
  end

  def nobody_is_chosen
    errors[:base] << "Please select more than one person." if male + female == NOBODY_IS_CHOSEN
  end

  def excessive_is_chosen
    errors[:base] << "Please select less than three people." if male + female > EXCESSIVE_ARE_CHOSEN
  end
end

# 同一人物による同じ日の同じ時間帯のmealを作れない要する。

# == Schema Information
#
# Table name: meals
#
#  id           :bigint(8)        not null, primary key
#  date         :date
#  female       :integer          not null
#  male         :integer          not null
#  note         :text(65535)
#  skype        :boolean
#  time         :string(255)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  foreigner_id :bigint(8)
#  location_id  :bigint(8)
#
# Indexes
#
#  index_meals_on_foreigner_id  (foreigner_id)
#  index_meals_on_location_id   (location_id)
#

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :only_foreigner, except: :index
  before_action :deserve_to_create_meal?, except: :index
  before_action :meal_num_get, only: [:new, :create]
  before_action :find_meal, only: [:edit, :update, :destroy]

  def index
    if foreigner?
      @foreigner_all_meals      = current_foreigner.meals
      @foreigner_offered_meals  = current_foreigner.meals.select { |my_meal| my_meal.already_offered? && !my_meal.already_matched? }
      @foreigner_matched_meals  = current_foreigner.meals.select(&:already_matched?)
    else
      @japanese_favor_meals   = current_japanese.favors.map(&:meal).delete_if(&:already_matched?)
      @japanese_offered_meals = current_japanese.matches.where(ok: false).map(&:meal)
      @japanese_matched_meals = current_japanese.matches.where(ok: true).map(&:meal)
    end
    render layout: "personal_user"
  end

  def new
    @meal = Meal.new
    Meal.all.each { |meal| meal.destroy if meal.date.past? }
  end

  def create
    @meal = current_foreigner.meals.build(meal_params)

    if @meal.save
      flash[:notice] = "meal succesfully created!!"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @meal.update(meal_params)
      flash[:success] = "Meal was successfully updated"
      redirect_to meals_path
    else
      render 'edit'
    end
  end

  def destroy
    if @meal.room.nil?
      Meal.find(@meal.id).destroy
      flash[:success] = "Meal was successfully deleted"
    end
    redirect_to meals_path
  end

  private

  def only_foreigner
    unless foreigner?
      flash[:warning] = t('flash.wrong_access')
      redirect_back(fallback_location: root_path)
    end
  end

  def deserve_to_create_meal?
    if current_foreigner.there_lack_attributes?
      flash[:warning] = "Please complete your profile or introduction."
      redirect_to edit_foreigner_registration_path
    end
  end

  def meal_num_get
    unless Meal.size_over?(current_foreigner)
      flash[:alert] = "Sorry. Maximum posts are five."
      redirect_to root_path
    end
  end

  def meal_params
    params.require(:meal).permit(:date, :time, :location_id, :male, :female, :skype)
  end

  def find_meal
    @meal = Meal.find(params[:id])
  end
end

app/views/meals/_meal.html.erb
<div class="mb-4 px-0 d-inline-block mx-3" style="background-color:#ffa47c;width:290px;border-radius:5px;filter:drop-shadow(1px 1px 4px rgba(0,0,0,0.7));">
  <div class="meal-top pt-2 d-flex bg-white flex-column" style="border-top-left-radius:5px;border-top-right-radius:5px;position:relative;">
    <div style="position:absolute;top:130px;right:10px;"  data-toggle="modal" data-target="#home-user-<%= meal.foreigner.id %>">
      <span class="fa-stack faa-wrench animated-hover" style="font-size:20px;filter:drop-shadow(1px 1px 2px rgba(0,0,0,0.9));">
        <i class="fas fa-circle fa-stack-2x text-white font-info"></i>
        <i class="fas fa-info fa-stack-1x" style="color:#008BBB;"></i>
      </span>
    </div>

    <% if japanese? && !meal.already_matched? %>
      <div style="position:absolute;top:8px;left:10px;">
        <% if !Favor.exists?(meal_id: meal.id, japanese_id: current_japanese.id) %>
          <%= link_to meal_favors_path(meal), method: :post do %>
            <i class="far fa-heart fa-2x text-danger meal-heart"></i>
          <% end %>
        <% else %>
          <%= link_to favor_path(Favor.find_by(meal_id: meal.id, japanese_id: current_japanese.id )), method: :delete do %>
            <i class="fas fa-heart fa-2x text-danger meal-heart"></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
    <div class="text-dark mx-auto d-flex">
      <div class="text-center pt-1">
        <%= image_tag meal.foreigner.image.url(:_700), class: "home-image mb-2 circle-image", size: "100x100", style: "border:solid 1.5px white;brder-radius:5px;filter:drop-shadow(1px 1px 3px rgba(0,0,0,0.5));"%>
        <div class="mb-1 mr-3 text-muted font-weight-bold" style="font-size:18px;" data-toggle="modal" data-target="#home-user-<%= meal.foreigner.id %>">
          <%= image_tag meal.foreigner.nation.flag.url, size: "33x20", class: "align-top mr-2", style: "filter:drop-shadow(2px 2px 3px rgba(0,0,0,0.3));" %>
          <%= meal.foreigner.name.truncate(13) %> , <%= meal.foreigner.age %>
        </div>
      </div>
    </div>
  </div>





  <div class="meal-bottom mx-auto pt-2 pb-1" style="border-radius:5px;width:245px;">

    <div class="ml-2 mt-1" style="padding:1px;font-size:17px;">
      <span class="fa-stack" style="font-size:14px;">
        <i class="fas fa-circle fa-stack-2x text-white"></i>
        <i class="fas fa-comment-dots fa-stack-1x meal-color" style="font-size:19px;"></i>
      </span>
      <span class="ml-1 mr-2 text-white">
        :
      </span>
      <span class="font-weight-bold text-white">
        <%= meal.foreigner.flng.pick_locale %>
        <% if meal.foreigner.slng && meal.foreigner.slng.lang_en != "none" %>
          <span class="text-white">
           /
          </span>
          <%= meal.foreigner.slng.pick_locale %>
        <% end %>
      </span>
    </div>

    <div class="ml-2" style="padding:1px;font-size:17px;">
      <span class="fa-stack" style="font-size:14px;">
        <i class="fas fa-circle fa-stack-2x text-white"></i>
        <i class="fas fa-calendar-alt fa-stack-1x meal-color" style="font-size:17px;"></i>
      </span>
      <span class="ml-1 mr-2 text-white">
        :
      </span>
      <span class="font-weight-bold text-white">
        <%= I18n.locale == :ja ? meal.date.strftime("%Y年%m月%d日(#{%w(日 月 火 水 木 金 土)[meal.date.wday]})") : meal.date.strftime("%dth %b %Y (%a)") %>
        </span>
      </span>
    </div>

    <div class="ml-2" style="padding:1px;font-size:17px;">
      <span class="fa-stack" style="font-size:14px;">
        <i class="fas fa-circle fa-stack-2x text-white"></i>
        <i class="fas fa-clock fa-stack-1x meal-color" style="font-size:19px;"></i>
      </span>
      <span class="ml-1 mr-2 text-white">
        :
      </span>
      <span class="font-weight-bold text-white">
        <%= meal.time %>
      </span>
    </div>

    <div class="ml-2" style="padding:1px;font-size:17px;">
      <span class="fa-stack" style="font-size:14px;">
        <i class="fas fa-circle fa-stack-2x text-white"></i>
        <i class="fas fa-map-marker-alt fa-stack-1x meal-color" style="font-size:19px;"></i>
      </span>
      <span class="ml-1 mr-2 text-white">
        :
      </span>
      <span class="font-weight-bold text-white">
        <%= meal.location.pick_locale %>, <%= meal.location.prefecture.pick_locale %>
      </span>
    </div>

    <div class="ml-1" style="padding:1px;font-size:17px;">
      <span class="fa-stack" style="font-size:14px;margin-left:4px;">
        <i class="fas fa-circle fa-stack-2x text-white"></i>
        <i class="fas fa-users fa-stack-1x meal-color" style="font-size:19px;"></i>
      </span>
      <span class="ml-1 mr-2 text-white">
        :
      </span>
      <span>
        <span class="font-weight-bold text-white">
          <span style="font-size:17px;"><%= meal.male + meal.female %></span> <%= t('ppl')%>
          <span style="font-size:14px;">
            (<i class="fas fa-male text-white ml-2"></i><span class="mr-1"> <%= meal.male%></span>+<i class="fas fa-female text-white ml-2"></i> <%= meal.female%> )
          </span>
        </span>
      </span>
    </div>

    <div class="ml-1" style="padding:1px;font-size:17px;">
      <span class="fa-stack" style="font-size:14px;margin-left:4px;">
        <i class="fas fa-circle fa-stack-2x text-white"></i>
        <i class="fab fa-skype fa-stack-1x meal-color" style="font-size:19px;"></i>
      </span>
      <span class="ml-1 mr-2 text-white">
        :
      </span>
      <span class="font-weight-bold text-white">
        <% if meal.skype == true%>
          <%= I18n.locale == :en ? "Yes, I want to." : "はい"%>
        <% else %>
          <%=  I18n.locale == :en ? "No, I don't want to." : "いいえ"%>
        <% end %>
      </span>
    </div>
  </div>

  <% if japanese? %>
    <div class="bg-white" style="padding:4px 0;border-top:dashed 2px white;border-bottom-left-radius:5px;border-bottom-right-radius:5px;">
      <% if meal.already_matched? %>
        <div class="d-flex justify-content-around py-1">
          <% if meal.room.japanese.id == current_japanese.id %>
            <%= button_to "マッチング済み。メッセージを送る", room_path(meal.room), method: :get, class: "btn font-weight-bold text-white mx-auto py-2 px-3 matched-btn", style: "background-color:red;border-radius:20px;display:block !important;font-size:14.5px;filter:drop-shadow(2px 2px 2px rgba(0,0,0,0.3));" %>
          <% else %>
            <%= button_to "マッチング済み", '#', method: :get, class: "btn font-weight-bold text-white mx-auto py-2 px-4", style: "background-color:#888888;border-radius:20px;display:block !important;font-size:14.5px;filter:drop-shadow(2px 2px 2px rgba(0,0,0,0.3));" %>
          <% end %>
        </div>
      <% elsif !meal.matches.find_by(japanese_id: current_japanese.id).nil? && !meal.matches.find_by(japanese_id: current_japanese.id).ok? %>
        <%= button_to "オファー済み、キャンセルする", match_path(meal.matches.find_by(japanese_id: current_japanese.id)), method: :delete, class: "btn mb-1 font-weight-bold text-white mx-auto py-2 px-2", style: "background-color:#FFCC00;border-radius:20px;display:block !important;font-size:17px;filter:drop-shadow(2px 2px 2px rgba(0,0,0,0.3));" %>
      <% elsif meal.matches.find_by(japanese_id: current_japanese.id).nil? %>
        <input class="btn mb-1 font-weight-bold text-white mx-auto py-2 px-4 offer-btn" style="background-color:#008BBB;border-radius:20px;display:block !important;font-size:17px;filter:drop-shadow(2px 2px 2px rgba(0,0,0,0.3));" type="submit" value="予算を決めてオファーする" data-toggle="modal" data-target="#offer_modal_<%= meal.id %>">
      <% end %>
    </div>
  <% end %>
</div>
<% if japanese? %>
  <%= render partial: 'shared/offer_confirmation', locals: { meal: meal } %>
<% end %>


<!-- MODAL -->
<div class="modal" id="home-user-<%= meal.foreigner.id %>" style="z-index:1500;margin-top:-70px;">
  <div class="modal-dialog">
    <div class="col mr-4 bg-lightorange text-center py-3" style="max-width:430px;min-width:430px;border-radius:10px;margin-bottom:100px;filter:drop-shadow(1px 0px 6px rgba(0,0,0,0.3));margin-top:30px;">
      <div class="left-image" style="margin-top:5px;">
        <button class="close" data-dismiss="modal">&times;</button>
        <%= image_tag meal.foreigner.image.url(:_700), size: "300x300", class: "border border-lightorange", style: "border-radius:10px;" %>
      </div>

      <div class="d-flex justify-content-center my-2 pb-1 border-bottom border-secondary">
        <div class="mr-2 h5 align-self-center" style="font-family:'Helvetica Neue';">
          <%= meal.foreigner.name %>
          <% if meal.foreigner.age %>
            <span class="font-weight-normal" style="font-size:20px;">, <%= meal.foreigner.age %></span>
          <% end %>
        </div>
        <div class="">
          <% if meal.foreigner.nation %>
            <%= image_tag meal.foreigner.nation.flag.url, size: "37x23", style: "border-radius:0px;" %>
          <% end %>
        </div>
      </div>

      <div class="d-flex mr-5 ml-4 mb-2">
        <div class="ml-4 py-1 border font-italic bg-darkorange border-darkorange text-white" style="min-width:129px;max-height:29px;border-radius:4px;font-size:13px;opacity:0.9;">
          <%= I18n.locale == :en ? "Nation" : "国籍" %>
        </div>
        <div class="ml-4 mb-0 h5 align-self-end text-left">
          <%= meal.foreigner.nation ? meal.foreigner.nation.pick_locale : "none" %>
        </div>
      </div>

      <div class="d-flex mr-5 ml-4 mb-2">
        <div class="ml-4 py-1 border font-italic bg-darkorange border-darkorange text-white" style="min-width:129px;max-height:29px;border-radius:4px;font-size:13px;opacity:0.9;">
          <%= I18n.locale == :en ? "Japanse Ability" : "日本語レベル" %>
        </div>
        <div class="ml-4 mb-0 h5 align-self-end text-left">
          <% if meal.foreigner.j_l == "中級" %>
            <%= I18n.locale == :en ? "intermediate" : "中級" %>
          <% elsif  meal.foreigner.j_l == "初級" %>
            <%= I18n.locale == :en ? "beginner" : "初級" %>
          <% else %>
            <%= I18n.locale == :en ? "advanced" : "上級" %>
          <% end %>
        </div>
      </div>

      <div class="d-flex mr-5 ml-4 mb-2">
        <div class="ml-4 py-1 border font-italic bg-darkorange border-darkorange text-white" style="min-width:129px;max-height:29px;border-radius:4px;font-size:13px;opacity:0.9;">
          <%= I18n.locale == :en ? "First Language" : "母国語" %>
        </div>
        <div class="ml-4 mb-0 h5 align-self-end text-left mr-3">
          <%= meal.foreigner.flng.pick_locale %>
        </div>
      </div>

      <div class="d-flex mr-5 ml-4 mb-2">
        <div class="ml-4 py-1 border font-italic bg-darkorange border-darkorange text-white" style="min-width:129px;max-height:29px;border-radius:4px;font-size:13px;opacity:0.9;">
          <%= I18n.locale == :en ? "Second Language" : "第2言語" %>
        </div>
        <div class="ml-4 mb-0 h5 align-self-end text-left mr-1">
          <%= meal.foreigner.slng ? meal.foreigner.slng.pick_locale : "none" %>
        </div>
      </div>

      <div class="pt-2 pl-4 text-left font-italic" style="border-radius:4px;font-size:17px;opacity:0.9;">
        <i class="fas fa-user mr-1"></i>
        <%= I18n.locale == :en ? "About me" : "自己紹介文" %>
      </div>
      <div class="container bg-white pt-3 border border-white" style="border-radius:10px;">
        <div class="mx-auto text-left text-muted" style="font-size:12px;border-radius:4px;padding:5px 18px 18px 18px;">
          <%= meal.foreigner.profile.intro  %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/meals/_new_edit_meal.html.erb
<div class="text-center new_meal" style="padding-top:15px;">
  <div class="row">
    <div class="col-xl-4 col-lg-5 col-md-7 col-sm-10 col-xs-8 mx-auto bg-white border-top border-darkorange px-0" style="border-radius:7px;filter:drop-shadow(10px 10px 10px rgba(0,0,0,0.4));">
      <div class="bg-darkorange text-white pt-3 h4" style="height:60px;border-top-left-radius:5px;border-top-right-radius:5px;">
        <i class="fas fa-coffee mr-2"></i>
        <%= current_page?(new_meal_path) ? "Compose new Meal" : "Edit Meal" %>
      </div>
      <%= form_for(@meal) do |f| %>
        <%= render 'shared/devise_errormes', object: f.object %>
        <div class="form-group">

          <div class="mb-45 mt-5" style="margin-right:54px;">
            <%= f.label :date, "Date(yyyy/mm/dd): ", class: "font-weight-bold ml-4" %>
            <span class="ml-2">
              <i class="fas fa-calendar-alt main-color"></i>
            </span>
            <%= f.text_field :date, placeholder: "select", class: "form-control  d-inline-block", id: "new-meal-datepicker", style: "width:150px;", autocomplete: 'off' %>
          </div>

          <div class="mb-45" style="margin-left:6px;">
            <%= f.label :time, "Time of Day :", class: "font-weight-bold ml-3" %>
            <span class="ml-1">
              <i class="fas fa-clock main-color"></i>
            </span>
            <%= f.select :time,  [["0am - 9am","0am-9am" ], ["09am - 12pm", "09am-12pm"],["12pm - 15pm", "12pm-15pm"],["15pm - 18pm ", "15pm-18pm"],["18pm - 21pm", "18pm-21pm"],["21pm - 24pm", "21pm-24pm"] ], { prompt: "select" } , { class: "form-control  d-inline-block", style: "width:150px;" } %>
          </div>

          <div class="mb-0" style="margin-right:55px;">
            <%= f.label :male, "How Many People? :", class: "font-weight-bold ml-4" %>
            <span class="ml-2">
              <i class="fas fa-male fa-lg main-color"></i>
            </span>
            <%= f.select :male,  [["0 male", 0], ["1 male", 1],["2 males", 2],["3 males", 3],], {}, { class: "form-control  d-inline-block", style: "width:150px;border-bottom-style:hidden !important;" }  %>
          </div>

          <div class="mb-45" style="margin-left:-4px;">
            <%= f.label :female, "(Maximum 3 people)", class: "text-muted", style: "font-size:10px;vertical-align:top;margin-left:28px !important;" %>
            <span class="ml-2">
              <i class="fas fa-female fa-lg main-color"></i>
            </span>
            <%= f.select :female,  [["0 female", 0], ["1 female", 1],["2 females", 2],["3 females", 3],], {} , { class: "form-control  d-inline-block", style: "width:150px;border-top-right-radius:0px !important;" } %>
          </div>

          <div class="mb-45" style="margin-left:48px;">
            <%= f.label :location, "Location :", class: "font-weight-bold ml-2" %>
            <span class="ml-2">
              <i class="fas fa-map-marker-alt main-color"></i>
            </span>
            <%= f.grouped_collection_select(:location_id, Prefecture.all, :locations, :name_en, :id, :name_en, { prompt: "select" } , { class: "form-control  d-inline-block", style: "width:150px;" } ) %>
          </div>

          <div class="mb-45" style="margin-left:53px;">
            <%= f.label :skype, "skype : ", class: "font-weight-bold ml-3" %>
            <span class="ml-2">
              <i class="fab fa-skype main-color"></i>
            </span>
            <%= f.select(:skype, [["Yes, I want to", 0], ["No, I don't want to", 1]], {}, { class: "form-control  d-inline-block", style: "width:150px;" } ) %>
          </div>

          <div class="actions pb-4">
            <%= f.submit "Post", class: "btn btn-darkorange btn-lg px-5" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/meals/edit.html.erb
<%= render 'new_edit_meal' %>

app/views/meals/new.html.erb
<%= render 'new_edit_meal' %>